-- task-service用スキーマ作成
-- Oracle XE起動時に自動実行される

-- 既存ユーザーがあれば削除（開発環境用）
BEGIN
  EXECUTE IMMEDIATE 'DROP USER TASK_DB CASCADE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP USER TASK_DB_TEST CASCADE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- TASK_DB ユーザー作成（開発用）
CREATE USER TASK_DB IDENTIFIED BY task_password;
GRANT CONNECT, RESOURCE, CREATE VIEW TO TASK_DB;
ALTER USER TASK_DB QUOTA UNLIMITED ON USERS;

-- TASK_DB_TEST ユーザー作成（テスト用）
CREATE USER TASK_DB_TEST IDENTIFIED BY task_test_password;
GRANT CONNECT, RESOURCE, CREATE VIEW TO TASK_DB_TEST;
ALTER USER TASK_DB_TEST QUOTA UNLIMITED ON USERS;

-- 確認用
SELECT username, account_status FROM dba_users WHERE username LIKE 'TASK_DB%';
