-- user-service用スキーマ作成
-- Oracle XE起動時に自動実行される

-- 既存ユーザーがあれば削除（開発環境用）
BEGIN
  EXECUTE IMMEDIATE 'DROP USER USER_DB CASCADE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP USER USER_DB_TEST CASCADE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- USER_DB ユーザー作成（開発用）
CREATE USER USER_DB IDENTIFIED BY user_password;
GRANT CONNECT, RESOURCE, CREATE VIEW TO USER_DB;
ALTER USER USER_DB QUOTA UNLIMITED ON USERS;

-- USER_DB_TEST ユーザー作成（テスト用）
CREATE USER USER_DB_TEST IDENTIFIED BY user_test_password;
GRANT CONNECT, RESOURCE, CREATE VIEW TO USER_DB_TEST;
ALTER USER USER_DB_TEST QUOTA UNLIMITED ON USERS;

-- 確認用
SELECT username, account_status FROM dba_users WHERE username LIKE 'USER_DB%';
